### PR TITLE
AbstractFloat and AbstractString depwarn fixes

### PR DESCRIPTION
**Pull request by kersulis**
Just taking care of a few deprecation warnings. I also removed a few leading spaces.

### CODE REVIEW

**Comment by jcrist** [comment]
Thanks for this. Looks like there's a few deprecation warnings in `tests/framework.jl`. Mind cleaning those up as well?

**Comment by kersulis** [comment]
Not sure why the CI build still fails. The deprecation warnings for Pkg.test() are gone locally.

**Comment by mfalt** [comment]
The changes proposed in this PR was included in #24 so I will close this now. We made some significant changes the last couple of weeks which made this a bit tricky to merge (or at least to verify since the tests and the travis code have also been changed). I appreciate that you took the time to fix this @kersulis and it inspired me to several other changes, thanks!

**Comment by kersulis** [comment]
:+1:

**Pull request closed without merging**
