### PR TITLE
d2c

### PR DESCRIPTION
**Pull request by StevenSiew**
Part of adding d2c() function

### CODE REVIEW

**Review by baggepinnen — CHANGES_REQUESTED** [review]
Thanks for the PR :)
It needs some tests to verify that it's working. I tried t on a simple system and got the wrong `B` matrix. 

It would be nice to test on a number of systems that `c2d` followed by `d2c` produces something similar to the original system.

**Comment by baggepinnen** [comment]
I think that this is an easier way to implement `d2c` for ZoH
```julia
julia> g1=ss([0 1; 0 0], [0,1], [1 0], 0)
StateSpace{Continuous,Int64,Array{Int64,2}}
A = 
 0  1
 0  0
B = 
 0
 1
C = 
 1  0
D = 
 0

Continuous-time state-space model

julia> g2 = c2d(g1,1)[1]
StateSpace{Discrete{Int64},Float64,Array{Float64,2}}
A = 
 1.0  1.0
 0.0  1.0
B = 
 0.5
 1.0
C = 
 1.0  0.0
D = 
 0.0

Sample Time: 1 (seconds)
Discrete-time state-space model

julia> exp([g1.A g1.B; zeros(1,3)]) # This is the computation done in c2d
3×3 Array{Float64,2}:
 1.0  1.0  0.5
 0.0  1.0  1.0
 0.0  0.0  1.0

julia> exp([g1.A g1.B; zeros(1,3)]) |> log # This is the inverse of the c2d
3×3 Array{Complex{Float64},2}:
 0.0+0.0im  1.0+0.0im  -9.71445e-17+0.0im
 0.0+0.0im  0.0+0.0im           1.0+0.0im
 0.0+0.0im  0.0+0.0im           0.0+0.0im

```
onte that I did not include the sample time for brevity.

**Comment by StevenSiew** [comment]
I did a quick test and it seems to work.
```
julia> P1
TransferFunction{Continuous,ControlSystems.SisoRational{Float64}}
         1.0
---------------------
1.0*s^2 + 2.0*s + 3.0

Continuous-time transfer function model

julia> S1 = ss(P1)
StateSpace{Continuous,Float64,Array{Float64,2}}
A = 
  0.0   1.0
 -3.0  -2.0
B = 
 0.0
 1.0
C = 
 1.0  0.0
D = 
 0.0

Continuous-time state-space model

julia> S_d, = c2d(S1,0.5)
(StateSpace{Discrete{Float64},Float64,Array{Float64,2}}
A = 
  0.7397292093468955  0.2786175523396482
 -0.8358526570189445  0.18249410466759897
B = 
 0.08675693021770156
 0.2786175523396482
C = 
 1.0  0.0
D = 
 0.0

Sample Time: 0.5 (seconds)
Discrete-time state-space model, [1.0 0.0 0.0; 0.0 1.0 0.0])

julia> Z = d2c(S_d)
StateSpace{Continuous,Float64,Array{Float64,2}}
A = 
 -6.661338147750939e-16   0.9999999999999998
 -2.9999999999999996     -2.0
B = 
 4.163336342344337e-16
 0.9999999999999996
C = 
 1.0  0.0
D = 
 0.0

Continuous-time state-space model
```

**Comment by StevenSiew** [comment]
This is too hard for me. I do not think there is a way to go from a continuous state space system to a discrete state space system such that det(A_d - I) == 0

So the question of what to do when det(A_d - I) == 0 is kinda silly.

Sure you can design a discrete system such that det(A_d - I) == 0 but then you cannot convert it to a continuous state space system using zero order hold method. You would have to use another different method.

**Comment by baggepinnen** [comment]
Closed in favor of 355

**Pull request closed without merging**
