### PR TITLE
update of showterm2 due to 'j' parameter removed from Polynomials.printsign

### PR DESCRIPTION
**Pull request by andrersimoes**
See issue #229.

### CODE REVIEW

**Comment by mfalt** [comment]
Could you also please set v0.5.3 as the lower limit for Polynimials.jl? I.e. add 
```
[compat]
Polynomials= "0.5.3"
```
to the Project.toml file

**Comment by andrersimoes** [comment]
Project.toml altered and tested inside an empty .julia directory. Please, check if it works on your side too.

**Comment by baggepinnen** [comment]
Nice, can we have a patch release for this as well?

**Comment by mfalt** [comment]
> 
> 
> Nice, can we have a patch release for this as well?

Yes, I think we have quite a few updates, especially regarding delay systems since the last version

**Comment by mfalt** [comment]
It seems like delay systems still dosn't have a tagged vesrion, so I'll take a look tomorrow and see what issues/PRs we can include in a 0.6 release this weekend. I think the delay systems should be bigger than a patch version. Any thoughts @baggepinnen ?

**Comment by baggepinnen** [comment]
The tagging of minor release indicates a breaking release for major version 0. If we should follow julias version of semver, we should only tag 0.6 if something has broken, otherwise it's a patch release. We could also consider tagging 1.0 if we think that the API will be stable from now on.

The downside of tagging a breaking release is that everyone that has a dependency on ControlSystems will have to update their compat file, otherwise they will block controlsystems from updating.

**Pull request merged**
