### PR TITLE
Add rlocus

### PR DESCRIPTION
**Pull request by mzaffalon**

### CODE REVIEW

**Comment by mzaffalon** [comment]
Addresses #764.

**Comment by baggepinnen** [comment]
Cool, thanks for this PR!

We should probably add the output arguments to the docstring as well since there's more than one. 

I've noticed that your editor/IDE appears to do some normalization of the code, removing white space etc. on lines unrelated to the PR. This is generally undesirable for pull requests since it adds a lot of noise in the git history, could you perhaps find a way to turn that off for repos that are not your own to avoid this?

**Comment by mzaffalon** [comment]
Sorry about the poor thought-out doc string.

Yes, I have set up Emacs to remove trailing white spaces. I thought white spaces after the code line end was unwanted, but if it is your wish not to do that, I will disable that feature.

**Comment by mzaffalon** [comment]
I see that there are tests for `rlocusplot`: do you think I should add any for `rlocus`, i.e. check against an analytical solution? From a quick check I saw a difference of 0.1-1.

**Comment by baggepinnen** [comment]
Unfortunately, the tests for `rlocusplot` are quite bad, it's hard to test plots properly :/ 
A test for `rlocus` would thus be very welcome :)

**Pull request merged**
