### PR TITLE
Remove matrix size from StateSpace types

### PR DESCRIPTION
**Pull request by baggepinnen**
Solves #399 and supersedes #400

### CODE REVIEW

**Comment by olof3** [comment]
Looks good, great to get rid of those fields. There were a lot of other fixes in #410, what about those?

**Comment by baggepinnen** [comment]
I accidentally included tons of unrelated commits from my working branch. They might make their way into master eventually, but I have a few PRs waiting to be merged before I can submit the rest of the changes.

**Comment by olof3** [comment]
Looked like there was a lot of useful stuff there :)

**Comment by baggepinnen** [comment]
Hmm, the failing test only fails on julia v1.5, not on julia v1.0 or nightly
https://github.com/JuliaControl/ControlSystems.jl/pull/411/checks?check_run_id=1714851690#step:6:251

**Pull request merged**
